### ISSUE TITLE
Error: unknown tag !<!lambda> (38:1)

### ISSUE THREAD

**Issue by liquidbear99** [dgrnbrg/appdaemon-configs#1]
When copying the yaml file for the ld2410b into the esp32 directory, home assistant gives the following error.

```
unknown tag !<!lambda> (38:1)

 35 |             }
 36 |             data.insert(data.en ...
 37 |             return data;
 38 | #value: [
------^
 39 | #  0xfd, 0xfc, 0xfb, 0xfa, 0x08 ...
 40 | #  0x48, 0x69, 0x4c, 0x69, 0x6e ...
```

**Comment by dgrnbrg** [comment]
Do you have more error context? What version of ESPHome are you using? Did you copy & paste the text in the file, or did you save/copy the the file?

I tried pushing a small fix. Try redownloading again and lmk if that fixes it.

**Comment by liquidbear99** [comment]
Looks like that fixed it!
